#
# Copyright (c) 2023, TRE-FX Consortium Members
# Copyright (c) 2023-2024, Arjuna Technologies Limited, Newcastle upon Tyne, Tyne and Wear, UK.
#

MVN = mvn

all:
	$(MVN) install

push: all

clean:
	$(MVN) clean

purge: clean
