apiVersion: v1
kind: Pod
metadata:
  name: analysis_datashield
  labels:
    app: datashield
spec:
  containers:
  - name: armadillo
    image: docker.io/datashield/armadillo3:test
    ports:
      - containerPort: 8080
        hostPort: 8080
    env:
      - name: RSERVE_HOST
        value: "localhost"
      - name: DEBUG
        value: "FALSE"
  - name: rserver
    image: docker.io/datashield/armadillo-rserver_caravan-yak:1.0.0
    ports:
      - containerPort: 6311
        hostPort: 6311
    env:
      - name: DEBUG
        value: "FALSE"
