#
# Copyright (c) 2023, TRE-FX Consortium Members
# Copyright (c) 2023-2024, Arjuna Technologies Limited, Newcastle upon Tyne, Tyne and Wear, UK.
#

apiVersion: v1
kind: Pod
metadata:
  name: demo-sde
  labels:
    app: sde
spec:
  containers:
  - name: activemq
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:latest
    ports:
      - containerPort: 5672
        hostPort: 5972
    env:
      - name: AMQ_USER
        value: "admin"
      - name: AMQ_PASSWORD
        value: "password"
  - name: webportal
    image: docker.io/risbic/sde-webportal:test
    ports:
      - containerPort: 80
        hostPort: 8090
  - name: mongo
    image: docker.io/library/mongo:latest
    volumeMounts:
      - mountPath: /data/db
        name: mongo-data
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "admin"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "password"
  - name: minio
    image: quay.io/minio/minio
    volumeMounts:
      - mountPath: /data
        name: minio-data
    env:
      - name: MINIO_ROOT_USER
        value: "admin"
      - name: MINIO_ROOT_PASSWORD
        value: "password"
    args: ["server", "/data", "--address", ":9000", "--console-address", ":9001"]
  - name: request_receiver
    image: docker.io/risbic/sde-request-receiver:test
    env:
      - name: DMZ_AMQPBROKER_HOST
        valueFrom:
          configMapKeyRef:
            name: demo-config
            key: dmz_amqpbroker_host
      - name: DMZ_AMQPBROKER_PORT
        valueFrom:
          configMapKeyRef:
            name: demo-config
            key: dmz_amqpbroker_port
  - name: request_checker
    image: docker.io/risbic/sde-request-checker:test
  - name: analysis_dispacher
    image: docker.io/risbic/sde-analysis-dispatcher:test
    env:
      - name: ANALYSIS_DS_AMQPBROKER_HOST
        valueFrom:
          configMapKeyRef:
            name: demo-config
            key: analysis_ds_amqpbroker_host
      - name: ANALYSIS_DS_AMQPBROKER_PORT
        valueFrom:
          configMapKeyRef:
            name: demo-config
            key: analysis_ds_amqpbroker_port
  - name: response_checker
    image: docker.io/risbic/sde-response-checker:test
  - name: response_sender
    image: docker.io/risbic/sde-response-sender:test
    env:
      - name: DMZ_AMQPBROKER_HOST
        valueFrom:
          configMapKeyRef:
            name: demo-config
            key: dmz_amqpbroker_host
      - name: DMZ_AMQPBROKER_PORT
        valueFrom:
          configMapKeyRef:
            name: demo-config
            key: dmz_amqpbroker_port
  - name: control
    image: docker.io/risbic/sde-control:test
  - name: devel
    image: docker.io/risbic/sde-devel:test
    volumeMounts:
      - mountPath: /data
        name: devel-data
  volumes:
    - name: devel-data
      hostPath:
        path: ./devel-data/sde
        type: DirectoryOrCreate
    - name: mongo-data
      hostPath:
        path: ./sde-data/mongo
        type: DirectoryOrCreate
    - name: minio-data
      hostPath:
        path: ./sde-data/minio
        type: DirectoryOrCreate
