apiVersion: v1
kind: Pod
metadata:
  name: demo-analysis-datashield
  labels:
    app: analysis-datashield
spec:
  containers:
  - name: activemq
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:latest
    ports:
      - containerPort: 5672
        hostPort: 6072
    env:
      - name: AMQ_USER
        value: "admin"
      - name: AMQ_PASSWORD
        value: "password"
  - name: analysis-datashield-adaptor
    image: docker.io/risbic/analysis-datashield-adaptor:latest
  - name: armadillo
    image: docker.io/risbic/analysis-datashield-armadillo:latest
    ports:
      - containerPort: 8080
        hostPort: 8100
    env:
      - name: DEBUG
        value: "FALSE"
    volumeMounts:
      - mountPath: /data
        name: analysis-datashield-armadillo
  - name: trefx-rserver
    image: docker.io/datashield/armadillo-rserver_ionic-aqueduct:1.0.0
    env:
      - name: DEBUG
        value: "FALSE"
  volumes:
    - name: analysis-datashield-armadillo
      hostPath:
        path: /tmp/analysis-data/datashield/armadillo
        type: DirectoryOrCreate
