#
# Copyright (c) 2023, Arjuna Technologies Limited, Newcastle upon Tyne, Tyne and Wear, UK.
#

apiVersion: v1
kind: Pod
metadata:
  name: demo-lab
spec:
  containers:
  - name: activemq
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:latest
    ports:
    - containerPort: 8161
      hostPort: 8161
    - containerPort: 5672
      hostPort: 5672
    env:
      - name: AMQ_USER
        value: "admin"
      - name: AMQ_PASSWORD
        value: "password"
  - name: mongo
    image: quay.io/domino/mongo
    volumeMounts:
      - mountPath: /data/db
        name: mongo-data
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "admin"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "password"
  - name: minio
    image: quay.io/minio/minio
    volumeMounts:
      - mountPath: /data
        name: minio-data
    ports:
    - containerPort: 9001
      hostPort: 9003
    env:
      - name: MINIO_ROOT_USER
        value: "admin"
      - name: MINIO_ROOT_PASSWORD
        value: "password"
    args: ["server", "/data", "--address", ":9000", "--console-address", ":9001"]
  - name: webportal
    image: docker.io/risbic/lab-webportal:gt
    ports:
    - containerPort: 80
      hostPort: 8082
    env:
      - name: NGINX_HOST
        value: "localhost"
      - name: NGINX_PORT
        value: "80"
  - name: request_creator
    image: docker.io/risbic/lab-request-creator:gt
  - name: response_processor
    image: docker.io/risbic/lab-response-processor:gt
  - name: request_sender
    image: docker.io/risbic/lab-request-sender:gt
  volumes:
    - name: mongo-data
      hostPath:
        path: /home/swheater/sde-demo/data/lab/mongo
        type: DirectoryOrCreate
    - name: minio-data
      hostPath:
        path: /home/swheater/sde-demo/data/lab/minio
        type: DirectoryOrCreate
