apiVersion: v1
kind: Pod
metadata:
  name: ds-minio
  labels:
    app: minio
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio
    ports:
      - containerPort: 9000
        hostPort: 8888
      - containerPort: 9001
        hostPort: 9001
    env:
      - name: MINIO_ROOT_USER
        value: "admin"
      - name: MINIO_ROOT_PASSWORD
        value: "password"
    volumeMounts:
      - mountPath: /data
        name: minio-data
    args: ["server", "/data", "--address", ":9000", "--console-address", ":9001"]
  volumes:
    - name: minio-data
      hostPath:
        path: ./minio-data
        type: DirectoryOrCreate
