crypt4gh:
    key: cert/ds.key
    pub: cert/ds.pub
    passphrase: trefx
tools:
    dockerCommand: podman
    encrypted_fs:
        type: gocryptfs
    engineMode: local
    gitCommand: git
    javaCommand: java
    staticBashCommand: bash-static
workDir: ./var/work_dir
cacheDir: ./var/cache_dir
