apiVersion: v1
kind: Pod
metadata:
  name: anal-datashield
  labels:
    app: datashield
spec:
  containers:
  - name: activemq
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:latest
    ports:
      - containerPort: 5672
        hostPort: 6072
    env:
      - name: AMQ_USER
        value: "admin"
      - name: AMQ_PASSWORD
        value: "password"
  - name: anal-datashield-adaptor
    image: docker.io/risbic/anal-datashield-adaptor:latest
  - name: armadillo
    image: docker.io/risbic/armadillo-trefx:latest
    ports:
      - containerPort: 8080
        hostPort: 8080
    env:
      - name: DEBUG
        value: "FALSE"
    volumeMounts:
      - mountPath: /data
        name: anal-datashield
  - name: rserver
    image: docker.io/datashield/armadillo-rserver_ionic-aqueduct:1.0.0
    ports:
      - containerPort: 6311
        hostPort: 6311
    env:
      - name: DEBUG
        value: "FALSE"
  volumes:
    - name: anal-datashield
      hostPath:
        path: ./anal-data/datashield
        type: DirectoryOrCreate
